[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let cmd = 'make'
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

# カラースキーム
[[plugins]]
repo = 'tomasr/molokai'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'

# ステータスライン
[[plugins]]
repo = 'Lokaltog/vim-powerline'

# インデント可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# アウトライン
[[plugins]]
repo = 'h1mesuke/unite-outline'

# ファイル(言語)の構文チェック
[[plugins]]
repo = 'scrooloose/syntastic'

# コメントサポート
[[plugins]]
repo = 'scrooloose/nerdcommenter'

# Python入力補完
[[plugins]]
repo = 'davidhalter/jedi-vim'

# 関数のリスト表示
[[plugins]]
repo = 'vim-scripts/taglist.vim'

# 管理者権限の必要なファイルを編集
[[plugins]]
repo = 'lambdalisue/suda.vim'

